import APIClient from '../../network/index'

const homeStore={
    state: {
        bannerItems:[],
        KanjiaItems:[],
        JingxuanItems:[],
        ZhuantiItems:[],
        kanjialist:[],
        zhuanlanlist:[],
        renqilist:[],
        yIng:[],
        xunmeng:[]
    },
    mutations: {//同步操作state 接受actions传过来的数据
        BANNER(state,items){
            state.bannerItems=[...items]
          },
        KANJIA(state,items){
              state.KanjiaItems=[...items]
          },
        JINGXUAN(state,items){
              state.JingxuanItems=[...items]
          },
          ZHUANTI(state,items){
              state.ZhuantiItems=[...items]
          },
          KanjiaList(state,items){
              state.kanjialist=[...items]
          },
          ZhuanlanList(state,items){
              state.zhuanlanlist=[...items]
          },
          RenqiList(state,items){
              state.renqilist=[...items]
          },
          Ying(state,items){
              console.log(items);
              state.yIng=[items]
          },
          Xunmeng(state,items){
            state.xunmeng=[items]
        }

    },
    actions: {//只能异步请求数据
        BANNERITM(context){
            APIClient.banner().then((res)=>{
                context.commit('BANNER',res.data.data)
            })
        },
        KANJIAITM(context){
            APIClient.getStoreList({params:{
                page:3,
                pageSize:3
            }}).then((res)=>{
                context.commit('KANJIA',res.data.data)
            })
        },
        JINGXUANITM(context){
            APIClient.homeJpzl({params:{
                pageSize:5
            }}).then((res)=>{
                context.commit('JINGXUAN',res.data.data)
            })
        },
        ZHUANTIITM(context){
            APIClient.getStoreList({params:{
                page:4,
                pageSize:4
            }}).then((res)=>{
                context.commit('ZHUANTI',res.data.data)
            })
        },
        KanJiaList(context){
            APIClient.getStoreList({
                params:{
                    page:3,
                    pageSize:10
                }
            }).then((res)=>{
                context.commit('KanjiaList',res.data.data)
            })
        },
        ZhuanLanList(context){
            APIClient.homeJpzl().then((res)=>{
                context.commit('ZhuanlanList',res.data.data)
            })
        },
        RenQiList(context){
            APIClient.getStoreList({
                params:{
                    page:3,
                    pageSize:10
                }
            }).then((res)=>{
                console.log(res);
                context.commit('RenqiList',res.data.data)
            })
        },
        YING(context){
            APIClient.ying({
                params:{
                   id:9845
                }
            }).then((res)=>{
                console.log(res);
                context.commit('Ying',res.data.data)
            })
        },
        XUNMENG(context){
            APIClient.ying({
                params:{
                   id:9846
                }
            }).then((res)=>{
                console.log(res);
                context.commit('Xunmeng',res.data.data)
            })
        },
    },
    modules: {
    }
}

export default homeStore